<a href="https://colab.research.google.com/github/archit-55/ML/blob/master/ML1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy


In [0]:
import numpy as np
a=np.array([2,5,7,99,1,4])
type(a)


In [0]:
b=np.array([12,17,11,199,4,6])
a

In [0]:
b

In [0]:
a[2]

In [0]:
a+b


In [12]:
a*2

array([  4,  10,  14, 198,   2,   8])

In [13]:
a**2

array([   4,   25,   49, 9801,    1,   16])

In [15]:
import numpy as np
#creating 1D array
a=np.array([2,3,5,79])
b=np.array([12,13,15,179])

#adding san=me D array
c=a+b
print(c)

#multi
m=a*b
print(m)

#add particular value in each element of array
a5=a+5
print(a5)

[ 14  16  20 258]
[   24    39    75 14141]
[ 7  8 10 84]


In [18]:
x=np.array([[2,5,8] , [3,6,1]])
print(x)

[[2 5 8]
 [3 6 1]]


In [19]:
x+7

array([[ 9, 12, 15],
       [10, 13,  8]])

In [21]:
y=x+7
print(y)


[[ 9 12 15]
 [10 13  8]]


In [22]:
x*2

array([[ 4, 10, 16],
       [ 6, 12,  2]])

In [23]:
x**2

array([[ 4, 25, 64],
       [ 9, 36,  1]])

In [24]:
z=np.array([[2,7],[3,8],[3,9],[9,4]  ])
z

array([[2, 7],
       [3, 8],
       [3, 9],
       [9, 4]])

In [25]:
x
x.shape


(2, 3)

In [26]:
z.shape

(4, 2)

In [27]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [28]:
x[1]

array([3, 6, 1])

In [29]:
z

array([[2, 7],
       [3, 8],
       [3, 9],
       [9, 4]])

In [30]:
z[0:2]

array([[2, 7],
       [3, 8]])

In [47]:
z[0:,1]

array([7, 8, 9, 4])

In [34]:
z[0:2,1]

array([7, 8])

In [35]:
z[0:2,0:2]

array([[2, 7],
       [3, 8]])

In [39]:
x[0:,[0,2]]

array([[2, 8],
       [3, 1]])

In [40]:
z[[0,2]]

array([[2, 7],
       [3, 9]])

In [46]:
z[[0,3],1]

array([7, 4])

In [48]:
x.reshape(3,2)

array([[2, 5],
       [8, 3],
       [6, 1]])

In [49]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [51]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [56]:
np.full ((4,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [57]:
np.full((5,5),9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])